export interface IProject {
  id: number,
  title: string,
  description: string,
  image: string,
  technologies: Technology[],
  link?: string,
  repository?: string,
  demo?: string,
  videoLink?: string
}

export interface ISkill {
  name: string,
  icon: string,
};

export enum Technology {
  ASP_NET = "ASP.NET",
  AWS = "AWS",
  Android = "Android",
  Angular = "Angular",
  Axios = "axios",
  Azure = "Azure",
  Bootstrap = "Bootstrap",
  Bcrypt = "Bcrypt",
  Bulma = "Bulma",
  C = "C",
  CPlusPlus = "C++",
  CSS = "CSS",
  CSharp = "C#",
  ChakraUI = "Chakra UI",
  D = "D",
  Dart = "Dart",
  Docker = "Docker",
  Dotnet = ".NET",
  Electron = "Electron",
  EntityFramework = "Entity Framework",
  Erlang = "Erlang",
  Express = "Express",
  FSharp = "F#",
  irebase = "Firebase",
  Flutter = "Flutter",
  Git = "Git",
  Go = "Go",
  GraphQL = "GraphQL",
  HTML = "HTML",
  Haskell = "Haskell",
  Heroku = "Heroku",
  HyperledgerFabric = "Hyperledger Fabric",
  Java = "Java",
  JavaScript = "JavaScript",
  Jwt = "JWT",
  Kotlin = "Kotlin",
  Kubernetes = "Kubernetes",
  Less = "Less",
  Lua = "Lua",
  Markdown = "Markdown",
  MaterialUi = "Material UI",
  Mongo = "MongoDB",
  Moongose = "moongose",
  MySQL = "MySQL",
  Netlify = "Netlify",
  Next = "Next.js",
  Node = "Node.js",
  Nuxt = "Nuxt.js",
  ObjectiveC = "Objective-C",
  PHP = "PHP",
  Perl = "Perl",
  Pinia = "Pinia",
  PostgreSQL = "PostgreSQL",
  Python = "Python",
  R = "R",
  React = "React",
  Reactstrap = "ReactStrap",
  Redis = "Redis",
  Redux = "Redux",
  Ruby = "Ruby",
  Rust = "Rust",
  SQL = "SQL",
  SQLite = "SQLite",
  Sass = "Sass",
  Scala = "Scala",
  Strapi = "Strapi",
  Stylus = "Stylus",
  StyledComponents = "Styled Components",
  Supertest = "SuperTest",
  Svelte = "Svelte",
  Swift = "Swift",
  Tailwind = "Tailwind",
  TypeScript = "TypeScript",
  Vercel = "Vercel",
  Vue = "Vue",
  iOS = "iOS",
  linux = "Linux"
}